FROM rasa/rasa-sdk:3.1.0

WORKDIR /app

COPY actions/actions.py /app/actions.py

RUN pip install --user --no-cache-dir openai boto3 python-dotenv beautifulsoup4

CMD ["rasa", "run", "actions", "--debug"]
