FROM rasa/rasa-sdk:3.5.1

WORKDIR /app
COPY . /app

# Install Python packages globally (inside container)
USER root

RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt && \
    chmod +x /app/start_actions.sh

EXPOSE 8000
#COPY start.sh /app/start.sh
#RUN chmod +x /app/start.sh 

CMD ["bash", "/app/start_actions.sh"]
